
-- Generated by ORDS REST Data Services 21.2.4.r2431032
-- Schema: ADMIN  Date: Sun Oct 03 08:25:39 2021 
--

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'ADMIN',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'admin',
      p_auto_rest_auth      => FALSE);
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'games',
      p_base_path      => '/games/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'games',
      p_pattern        => 'games/:id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'games',
      p_pattern        => 'games/:id',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select * from games where id=:id');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'games',
      p_pattern        => 'games',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'games',
      p_pattern        => 'games',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select * from games');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'games',
      p_pattern        => 'games',
      p_method         => 'PUT',
      p_source_type    => 'plsql/block',
      p_items_per_page => 25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'begin
    update games set DEVELOPER=:developer, MINAGE=:minage, CATEGORY_ID=:category_id,NAME=:name WHERE id=:id;
    : status_code:=201;
end;');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'games',
      p_pattern        => 'games',
      p_method         => 'DELETE',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN
    delete from games where id=:id;
    : status_code:=204;
end;');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'games',
      p_pattern        => 'games',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page => 25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'begin
    insert into games(id,developer,minage,category_id,name) values(:id,:developer,:minage,:category_id,:name);
    : status_code:=201;
end;');

    
        
COMMIT;

END;